version: '3.9'
services:
  api1:
    build: .
    container_name: monkeytype-ranking
    volumes:
      - ./data:/usr/app/data
    networks:
      - proxy
    restart: always

networks:
  proxy:
    external: true
